### ISSUE TITLE
java.lang.ClassNotFoundException from git clone

### ISSUE THREAD

**Issue by zhengmin317** [wallerlab/yoink#1]
Running jar file from git clone  has an error: 
    java.lang.ClassNotFoundException: org.wallerlab.yoink.Yoink

While runing jar file from http://wallerlab.github.io/yoink/, no error.

**Comment by zhengmin317** [comment]
It can be fixed by changing the parent folder name "yoink" to something else.
Then do : ./gradlew clean build
                java -jar Yoink-0.0.1.jar

**Comment by mpwaller** [comment]
in your old project it was yoink-multi, and now it is just yoink. This might be the reason? we need a better solution. Changing the name of the directory is not ideal

**Comment by zhengmin317** [comment]
I have tried as long as the parent folder not named as "yoink" or "Yoink", it works.
Maybe we can change the project name on github.

**Comment by mpwaller** [comment]
哈哈。。。不

**Comment by zhengmin317** [comment]
We can change the project name on github to "Y-oink" or "Yo-ink" or "Yoink!"

**Comment by mpwaller** [comment]
不。。。谢谢
