### ISSUE TITLE
javadocs errors and warnings.

### ISSUE THREAD

**Issue by mpwaller** [wallerlab/yoink#12]
after running 
./gradlew alljavadoc

I get lots of errors and warnings. I guess some things have slipped by, because we dont manually run this too often.

**Comment by zhengmin317** [comment]
Hi Mark,
First I did "  ./gradlew clean build "
then "./gradlew alljavadoc"

BUILD SUCCESSFUL

No error.

**Comment by zhengmin317** [comment]
Also I tried:
- ./gradlew clean*
- ./gradlew bootRun*

_./gradlew alljavadoc_

BUILD SUCCESSFUL

No error.

**Comment by mpwaller** [comment]
Did you try this on the main branch?
I had to fix a lot of the javadocs to make it build. 
Maybe you don't have a clean fresh version from github? 
I try and do a fresh clone before testing it - but this takes me over an hour to clone at the moment.
the allJavadoc is now also on the travis-ci so we will know if this becomes a problem.

**Comment by zhengmin317** [comment]
I had a fresh clone.
I tried for master and bootRun branch, no error from alljavadoc.
