### ISSUE TITLE
pyoink

### ISSUE THREAD

**Issue by mpwaller** [wallerlab/yoink#16]
What does this class do? it calls yoink from Python- but why? only for clustering? will it use sci-kit?

**Comment by zhengmin317** [comment]
It's the python interface to yoink.
Yoink can be called in python script instead of external program.

**Comment by mpwaller** [comment]
I still don't know what it is for, I know it is an interface - but why do we have it? what are you planning to use it for? can you explain a bit more, thanks!

ok, I moved it to yoink-core-plugin, I think it is better there.

**Comment by zhengmin317** [comment]
python environment like ASE,  just needs to import pyoink. Pyoink is 
module/library.

Otherwise without pyoink, ASE needs to use os.system('java -jar yoink.jar')
